site_name: Sequelize Mock
site_description: Sequelize Mock is a Mocking Library for code relying on Sequelize ORM Models
site_favicon: favicon.png
site_url: http://sequelize-mock.readthedocs.io/
repo_url: https://github.com/BlinkUX/sequelize-mock
theme: readthedocs
extra_css:
- //cdnjs.cloudflare.com/ajax/libs/highlight.js/9.7.0/styles/vs.min.css
extra_javascript:
- //cdnjs.cloudflare.com/ajax/libs/highlight.js/8.4/highlight.min.js
pages:
- Home: 'index.md'
- Documentation:
  - 'Getting Started': 'docs/getting-started.md'
  - 'Creating Mock Objects': 'docs/creating-mocks.md'
#- Misc:
#  - 'Changelog': 'changelog.md'
